Repository civictheme/uikit, pull requests merged in 2024-06, with the labels that each got.

#182 [#58] Added Field as a molecule-level component.
  components/00-base/base.utils.js
  components/01-atoms/fieldset/fieldset.stories.js
  components/02-molecules/field/field.scss
  components/02-molecules/field/field.stories.js
  components/02-molecules/field/field.twig
  components/02-molecules/form-element/form-element.stories.js
  components/02-molecules/form-element/form-element.twig
  components/02-molecules/group-filter/group-filter.stories.js
  components/03-organisms/list/list.stories.js
Labels: PR: Needs review

#188 [126] Created Checkbox group & updated checkbox element.
  components/00-base/base.utils.js
  components/01-atoms/checkbox-group/checkbox-group.stories.js
  components/01-atoms/checkbox-group/checkbox-group.twig
  components/01-atoms/checkbox/checkbox.stories.js
  components/01-atoms/checkbox/checkbox.twig
Labels: PR: Requires more work

#190 [#59] Updated Field usage. Part 1
  components/00-base/base.utils.js
  components/01-atoms/checkbox-group/checkbox-group.stories.js
  components/01-atoms/checkbox-group/checkbox-group.twig
  components/01-atoms/radio-group/radio-group.stories.js
  components/01-atoms/radio-group/radio-group.twig
  components/01-atoms/select/select.stories.js
  components/01-atoms/textarea/textarea.stories.js
  components/01-atoms/textfield/textfield.stories.js
  components/02-molecules/field/field.stories.js
  components/02-molecules/field/field.twig
Labels: PR: Needs review

#210 Updated the Storybook About Page.
  assets/icons/document.svg
  assets/icons/layer.svg
  assets/icons/layers.svg
  assets/icons/lock-file.svg
  assets/icons/lock-gallery.svg
  assets/icons/mobile.svg
  assets/icons/users.svg
  assets/icons/water-drop.svg
  assets/icons/web.svg
  components/00-base/about/about.stories.scss
  components/00-base/about/about.stories.twig
Labels: PR: Needs review

#208 [#201] Fixed Side Navigation is missing left stripe.
  components/03-organisms/side-navigation/side-navigation.scss
Labels: PR: Needs review

#216 [#201] Fixed Left stripe missing for child active items for both themes for side navigation component.
  components/00-base/_variables.components.scss
Labels: PR: Needs review

#222 Updated missing default knobs.
  components/01-atoms/chip/chip.stories.js
  components/01-atoms/content-link/content-link.stories.js
  components/01-atoms/label/label.stories.js
  components/01-atoms/link/link.stories.js
  components/01-atoms/table/table.stories.js
  components/01-atoms/tag/tag.stories.js
  components/02-molecules/attachment/attachment.stories.js
  components/02-molecules/callout/callout.stories.js
  components/02-molecules/event-card/event-card.stories.js
  components/02-molecules/group-filter/group-filter.stories.js
  components/02-molecules/navigation-card/navigation-card.stories.js
  components/03-organisms/slider/slider.stories.js
Labels: PR: AUTOMERGE

#249 [#15] Added patch for stuck knobs.
  package.json
  patches/@storybook+addon-knobs+6.4.0.patch
Labels: PR: Needs review

#267 Fixed column gaps to be larger when only a single sidebar is present.
  components/00-base/layout/layout.scss
Labels: PR: Ready for test

#276 Fixed sidebar gap on `Layout` using masonry with JS fallback.
  components/00-base/layout/layout.js
  components/00-base/layout/layout.scss
  components/00-base/layout/layout.stories.js
Labels: PR: Needs review

#295 Update the Field's SCSS to set that line height.
  components/02-molecules/field/field.scss
  components/02-molecules/field/field.stories.js
Labels: PR: Needs review
