Repository civictheme/uikit, pull requests merged in 2025-05, with the labels that each got.

#510 [#511] Update storybook to 8.6.7
  .storybook/preview.js
  package-lock.json
  package.json
Labels: PR: Needs review

#573 Updated GHA for SDC.
  .github/workflows/drupal11-workflow.yml
  .github/workflows/test-drupal.yml
Labels: PR: Needs review

#572 Added github action for validation SDC components.
  .github/workflows/test-drupal.yml
Labels: PR: Needs review

#588 Added build script to setup local Drupal site for SDC development.
  .github/workflows/test-drupal.yml
  .github/workflows/visual-regression.yml
  .gitignore
  README.md
  composer.json
  tools/sdc/.gitignore
  tools/sdc/README.md
  tools/sdc/build.sh
  tools/sdc/ct_dev/ct_dev.info.yml
  tools/sdc/ct_dev/ct_dev.module
  tools/visual-diff/config/config.json
  tools/visual-diff/lib/config.mjs
  tools/visual-diff/lib/screenshot.mjs
  tools/visual-diff/lib/server.mjs
  tools/visual-diff/lib/templates/homepage.html
Labels: PR: Needs review

#589 [#590] Fixed 0 width container on mobile due to xs breakpoint of 0 width.
  packages/sdc/components/00-base/mixins/_grid.scss
  packages/sdc/components/03-organisms/navigation/navigation.css
  packages/twig/components/00-base/mixins/_grid.scss
Labels: PR: Needs review

#593 Added fix for linux local build.
  package.json
  tools/sdc/build.sh
Labels: PR: Needs review

#532 [#3516354] - Fixed civictheme dir auto-detect to work for base & subthemes.
  package-lock.json
  packages/twig/build.js
Labels: PR: Needs review

#618 Fixed GHA to skip netlify deployment comments on `main` branch.
  .github/workflows/test.yml
  .github/workflows/visual-regression.yml
Labels: PR: Needs review, PR: URGENT

#617 Fixed SDC validation not picking up errors.
  .github/workflows/test-drupal.yml
  packages/sdc/components/02-molecules/figure/figure.component.yml
Labels: PR: Needs review

#619 [#3525675] Fixed callout padding to avoid CSS specificity.
  packages/sdc/components/01-atoms/fieldset/__snapshots__/fieldset.test.js.snap
  packages/sdc/components/01-atoms/paragraph/__snapshots__/paragraph.test.js.snap
  packages/sdc/components/01-atoms/paragraph/paragraph.component.yml
  packages/sdc/components/01-atoms/paragraph/paragraph.css
  packages/sdc/components/01-atoms/paragraph/paragraph.scss
  packages/sdc/components/01-atoms/paragraph/paragraph.twig
  packages/sdc/components/02-molecules/accordion/__snapshots__/accordion.test.js.snap
  packages/sdc/components/02-molecules/attachment/__snapshots__/attachment.test.js.snap
  packages/sdc/components/02-molecules/callout/__snapshots__/callout.test.js.snap
  packages/sdc/components/02-molecules/callout/callout.css
  packages/sdc/components/02-molecules/callout/callout.scss
  packages/sdc/components/02-molecules/callout/callout.twig
  packages/sdc/components/02-molecules/event-card/__snapshots__/event-card.test.js.snap
  packages/sdc/components/02-molecules/navigation-card/__snapshots__/navigation-card.test.js.snap
  packages/sdc/components/02-molecules/next-step/__snapshots__/next-step.test.js.snap
  packages/sdc/components/02-molecules/promo-card/__snapshots__/promo-card.test.js.snap
  packages/sdc/components/02-molecules/publication-card/__snapshots__/publication-card.test.js.snap
  packages/sdc/components/02-molecules/snippet/__snapshots__/snippet.test.js.snap
  packages/sdc/components/03-organisms/campaign/__snapshots__/campaign.test.js.snap
  packages/sdc/components/03-organisms/list/__snapshots__/list.test.js.snap
  packages/sdc/components/03-organisms/promo/__snapshots__/promo.test.js.snap
  packages/twig/components/01-atoms/fieldset/__snapshots__/fieldset.test.js.snap
  packages/twig/components/01-atoms/paragraph/__snapshots__/paragraph.test.js.snap
  packages/twig/components/01-atoms/paragraph/paragraph.scss
  packages/twig/components/01-atoms/paragraph/paragraph.twig
  packages/twig/components/02-molecules/accordion/__snapshots__/accordion.test.js.snap
  packages/twig/components/02-molecules/attachment/__snapshots__/attachment.test.js.snap
  packages/twig/components/02-molecules/callout/__snapshots__/callout.test.js.snap
  packages/twig/components/02-molecules/callout/callout.scss
  packages/twig/components/02-molecules/callout/callout.twig
  packages/twig/components/02-molecules/event-card/__snapshots__/event-card.test.js.snap
  packages/twig/components/02-molecules/navigation-card/__snapshots__/navigation-card.test.js.snap
  packages/twig/components/02-molecules/next-step/__snapshots__/next-step.test.js.snap
  packages/twig/components/02-molecules/promo-card/__snapshots__/promo-card.test.js.snap
  packages/twig/components/02-molecules/publication-card/__snapshots__/publication-card.test.js.snap
  packages/twig/components/02-molecules/snippet/__snapshots__/snippet.test.js.snap
  packages/twig/components/03-organisms/campaign/__snapshots__/campaign.test.js.snap
  packages/twig/components/03-organisms/list/__snapshots__/list.test.js.snap
  packages/twig/components/03-organisms/promo/__snapshots__/promo.test.js.snap
Labels: PR: Ready to be merged

#620 [#3525673] Fixed back-to-top not resolving storybook dependencies.
  packages/sdc/components/02-molecules/back-to-top/__snapshots__/back-to-top.test.js.snap
  packages/sdc/components/02-molecules/back-to-top/back-to-top.css
  packages/sdc/components/02-molecules/back-to-top/back-to-top.scss
  packages/sdc/components/02-molecules/back-to-top/back-to-top.stories.twig
  packages/sdc/components/02-molecules/back-to-top/back-to-top.test.js
  packages/sdc/components/02-molecules/back-to-top/back-to-top.twig
  packages/sdc/components/04-templates/page/__snapshots__/page.test.js.snap
  packages/twig/components/02-molecules/back-to-top/__snapshots__/back-to-top.test.js.snap
  packages/twig/components/02-molecules/back-to-top/back-to-top.scss
  packages/twig/components/02-molecules/back-to-top/back-to-top.test.js
  packages/twig/components/02-molecules/back-to-top/back-to-top.twig
  packages/twig/components/04-templates/page/__snapshots__/page.test.js.snap
Labels: PR: Ready to be merged

#516 [#514] Updated field message background colour.
  packages/sdc/components/00-base/_variables.components.scss
  packages/twig/components/00-base/_variables.components.scss
Labels: PR: Ready to be merged
